apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite
  namespace: argocd
spec:
  destination:
    namespace: mysite
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./mysite
    repoURL: https://github.com/marconesns/mysite-app.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
