apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysite
  name: mysite
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: mysite
  type: NodePort
status:
  loadBalancer: {}
